### ISSUE TITLE
Consider dropping docker container and using pak instead

### ISSUE THREAD

**Issue by hadley** [mrworthington/irs_migration_data#1]
I _think_ this will simplify your workflow and speed up package installs. I'm doing something pretty similar in https://github.com/hadley/houston-pollen/blob/main/.github/workflows/scrape.yaml, where I rely on https://github.com/hadley/houston-pollen/blob/main/.github/workflows/scrape.yaml#L18-L20 to install the packages I've defined in my `DESCRIPTION` file. pak will use public package manager to get binaries, which should speed up install time.

**Comment by mrworthington** [comment]
Thanks @Hadley! Overall runtimes on the action seem to be similar after the first run was cached, but it removes the docker setup. In the future, I would absolutely prefer the pak setup vs. docker given how easy it was to get the package build organized with pak vs. docker. Also going to explore the gha package I saw your in your repo.
